#!/bin/sh
#
# Copyright (C) 2026  Henrique Almeida <me@h3nc4.com>
#
# This file is part of HyperGesture.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Names the image the CI suite runs in, and exports the docker invocation its steps use.
# A change touching the image inputs is built from this checkout, so the suite exercises
# the candidate rather than the published image it is about to replace. Nothing is pushed:
# the image stays in this runner's daemon, which is why callers reach it through docker run
# instead of a container job, and why every job resolves this for itself.
#
# Called by the action beside it. Reads PUBLISHED_REPO and BASE_SHA, writes image to
# GITHUB_OUTPUT and DEV_IMAGE and DEV_RUN to GITHUB_ENV.

set -eu

: "${PUBLISHED_REPO:?PUBLISHED_REPO is not set}"
: "${GITHUB_OUTPUT:?GITHUB_OUTPUT is not set. This runs under GitHub Actions.}"
: "${GITHUB_ENV:?GITHUB_ENV is not set. This runs under GitHub Actions.}"

cd "${GITHUB_WORKSPACE:?GITHUB_WORKSPACE is not set. This runs under GitHub Actions.}"

workdir="/workspace"

# A first push to a branch reports an all-zero base and has nothing to compare against, so
# treat the image as untouched.
changed=""
case "${BASE_SHA:-}" in
  "" | 0000000000000000000000000000000000000000) ;;
  *)
    if git cat-file -e "${BASE_SHA}^{commit}" 2>/dev/null; then
      changed="$(git diff --name-only "${BASE_SHA}" HEAD -- \
        docker/dev.Dockerfile scripts/entrypoint.sh scripts/switch-user.sh)"
    else
      changed="(base ${BASE_SHA} unreachable)"
    fi
    ;;
esac

if [ -z "${changed}" ]; then
  image="${PUBLISHED_REPO}:$(cat .github/VERSION)"
  echo "Image inputs untouched; using ${image}" >&2
else
  image="${PUBLISHED_REPO##*/}:candidate"
  echo "Image inputs changed, building ${image} from this checkout:" >&2
  echo "${changed}" | sed 's/^/  /' >&2
  set -- build
  if [ -n "${CACHE_FROM:-}" ] || [ -n "${CACHE_TO:-}" ]; then
    set -- buildx build --load
    if [ -n "${CACHE_FROM:-}" ]; then set -- "$@" --cache-from "${CACHE_FROM}"; fi
    if [ -n "${CACHE_TO:-}" ]; then set -- "$@" --cache-to "${CACHE_TO}"; fi
  fi
  docker "$@" -f docker/dev.Dockerfile -t "${image}" .
fi

uid="$(id -u)"
gid="$(id -g)"

case "${PWD}" in
  *"'"*)
    echo "The checkout path contains a single quote, which cannot be quoted here." >&2
    exit 1
    ;;
  *) ;;
esac

runner="${RUNNER_TEMP:-/tmp}/dev-run"
{
  echo '#!/bin/sh'
  echo '# Generated by .github/actions/dev-image. Runs one command in the dev image.'
  printf 'exec docker run --rm --user %s:%s --entrypoint /bin/bash' "${uid}" "${gid}"
  printf " -v '%s':'%s' -e HOME=/tmp -w '%s'" "${PWD}" "${workdir}" "${workdir}"
  if [ -n "${DOCKER_ARGS:-}" ]; then
    printf ' %s' "${DOCKER_ARGS}"
  fi
  printf " '%s' \"\$@\"\n" "${image}"
} >"${runner}"
chmod +x "${runner}"

echo "image=${image}" >>"${GITHUB_OUTPUT}"
{
  echo "DEV_IMAGE=${image}"
  echo "DEV_RUN=${runner}"
} >>"${GITHUB_ENV}"
